[package]
name = "oxidized_navigation"
description = "A Nav-Mesh generation plugin for Bevy Engine."
version = "0.7.0"
edition = "2021"

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/TheGrimsey/oxidized_navigation"
repository = "https://github.com/TheGrimsey/oxidized_navigation"

keywords = ["gamedev", "navmesh", "navmesh-generation", "bevy"]
categories = ["game-development"]

[features]
default = ["rapier"]
rapier = ["bevy_rapier3d"]
xpbd = ["bevy_xpbd_3d"]
debug_draw = []

[[example]]
name = "blocking_async_rapier"
required-features = ["debug_draw", "rapier"]

[[example]]
name = "blocking_async_xpbd"
required-features = ["debug_draw", "xpbd"]

[[example]]
name = "heightfield"
required-features = ["debug_draw", "rapier"]

[[example]]
name = "parry"
required-features = ["debug_draw"]

[dependencies]
bevy = { version = "0.11", default-features = false }
bevy_rapier3d = { version = "0.22", optional = true }
bevy_xpbd_3d = { version = "0.2", optional = true }
parry3d = "0.13.5"
smallvec = { version = "1.10", features = ["union"] }
[dev-dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "x11",
    "tonemapping_luts",
    "ktx2",
    "zstd",
] }
futures-lite = "1.12.0"
# bevy_editor_pls = "0.4.0"
